import {habitats, portraits} from './data.js';
import {loadRecords, saveRecords, validateRecords, freshRecords} from './store.js';
const main = document.querySelector('main');
const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records, storageError = '', query = '', habitat = 'All habitats', status = 'all', sort = 'name', dirty = false;
try { records = loadRecords(localStorage); } catch { records = freshRecords(); storageError = 'Saved data could not be loaded. Showing the starter collection. Export it before replacing your saved data.'; }
const photo = (r, extra='', large=false) => {
  const position = large
    ? `${(r.portrait % 2) * 100}% ${Math.floor((r.portrait % 4) / 2) * 100}%`
    : `${(r.portrait % 7) * 100 / 6}% ${Math.floor(r.portrait / 7) * 25}%`;
  const source = large ? `background-image:url('frog-detail-${Math.floor(r.portrait / 4)}.png');background-size:200% 200%;` : '';
  return `<div class="portrait p${r.portrait} ${extra}" style="${source}background-position:${position}" role="img" aria-label="${escape(portraits[r.portrait])}, a fictional frog portrait"></div>`;
};
function toast(message) { const el=document.querySelector('#toast'); el.textContent=message; el.classList.add('visible'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('visible'),4000); }
function persist(next) { try { records=saveRecords(localStorage,next); storageError=''; return true; } catch (error) { toast(`Could not save. ${error.message} Export your collection or enable browser storage, then try again.`); return false; } }
const options=(values,selected)=>values.map(v=>`<option value="${escape(v)}" ${v===selected?'selected':''}>${escape(v)}</option>`).join('');
const badge=r=>`<span class="badge ${r.habitat.toLowerCase().replaceAll(' ','-')}">${escape(r.habitat)}</span>`;
function route() {
  dirty=false;
  const hash=location.hash.slice(1)||'/';
  const admin=hash.startsWith('/admin');
  document.querySelector('#nav-guide').setAttribute('aria-current',admin?'false':'page');
  document.querySelector('#nav-admin').setAttribute('aria-current',admin?'page':'false');
  document.body.classList.toggle('admin',admin);
  document.title = `${admin?'Manage frogs':'Field guide'} · FrogDB`;
  if(hash==='/' || hash==='/#collection' || hash==='collection' || hash==='main') catalog();
  else if(hash==='/admin') dashboard();
  else if(hash==='/admin/new') editor();
  else if(hash.startsWith('/admin/edit/')) editor(records.find(r=>r.id===hash.slice(12)));
  else if(hash.startsWith('/frog/')) detail(records.find(r=>r.id===hash.slice(6)&&r.status==='published'));
  else notFound();
  window.scrollTo(0,0);
}
function banner() { return storageError?`<p class="notice" role="alert">${escape(storageError)}</p>`:''; }
function catalog() {
  const featured=records.find(r=>r.status==='published');
  main.innerHTML=`${banner()}<section class="hero"><div class="hero-copy"><h1>Small frogs.<br><em>Big personalities.</em></h1><p>A field guide to the almost-believable. Meet our collection of curious amphibians, one wonderfully weird frog at a time.</p><a class="button" href="#collection">Meet the frogs <span aria-hidden="true">↓</span></a><span class="hero-note">Entirely fictional. Endlessly fascinating.</span></div>${featured?`<a class="hero-specimen" href="#/frog/${featured.id}">${photo(featured,'',true)}<div class="specimen-caption"><span><strong>${escape(featured.name)}</strong><i>${escape(featured.scientific)}</i></span><span class="round-arrow" aria-hidden="true">↗</span></div><span class="photo-sticker">A very good frog.</span></a>`:'<div class="empty-hero"><h2>A pond full of possibilities.</h2><p>Publish your first frog in Manage frogs.</p></div>'}</section><section id="collection" class="collection"><div class="section-heading"><div><h2>The field guide</h2><p>Get to know the locals.</p></div><span id="result-count" aria-live="polite"></span></div><div class="filters"><label class="search"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg><span class="sr-only">Search frogs</span><input id="search" type="search" placeholder="Search by name, species, personality or location…" value="${escape(query)}"></label><label><span class="sr-only">Habitat</span><select id="habitat">${options(['All habitats',...habitats],habitat)}</select></label><label><span class="sr-only">Sort frogs</span><select id="sort"><option value="name" ${sort==='name'?'selected':''}>Name: A to Z</option><option value="size" ${sort==='size'?'selected':''}>Size: smallest first</option></select></label></div><div id="frog-grid" class="frog-grid"></div></section><section class="field-note"><svg viewBox="0 0 50 50" aria-hidden="true"><path d="M25 43V14M25 30C4 32 5 9 8 6c17 2 18 16 17 24ZM25 23C26 8 41 6 44 9c0 15-11 19-19 14Z" fill="none" stroke="currentColor" stroke-width="2"/></svg><div><h2>Nature-ish, by design.</h2><p>The species, field notes and portraits here are invented. Consider this a small celebration of the very big personalities hiding in the undergrowth.</p></div><a href="#/admin">Tend the collection <span aria-hidden="true">↗</span></a></section>`;
  wireFilters(false); drawCatalog();
}
function filtered(admin=false) { return records.filter(r=>(admin||r.status==='published')&&(habitat==='All habitats'||r.habitat===habitat)&&(!admin||status==='all'||r.status===status)&&[r.name,r.scientific,r.temperament,r.location].some(v=>v.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>sort==='size'?a.size-b.size:a.name.localeCompare(b.name)); }
function wireFilters(admin) {
  document.querySelector('#search').addEventListener('input',e=>{query=e.target.value;admin?drawRows():drawCatalog();});
  document.querySelector('#habitat').addEventListener('change',e=>{habitat=e.target.value;admin?drawRows():drawCatalog();});
  document.querySelector('#sort')?.addEventListener('change',e=>{sort=e.target.value;drawCatalog();});
}
function empty(message) {return `<div class="empty"><h3>No frogs in sight.</h3><p>${message}</p><button class="button secondary" id="clear-filters">Clear filters</button></div>`;}
function clearFilters(callback){document.querySelector('#clear-filters')?.addEventListener('click',()=>{query='';habitat='All habitats';status='all';callback();});}
function drawCatalog(){const list=filtered();document.querySelector('#result-count').textContent=`${list.length} ${list.length===1?'frog':'frogs'} to discover`;document.querySelector('#frog-grid').innerHTML=list.length?list.map(r=>`<article class="frog-card"><a href="#/frog/${r.id}" class="card-photo">${photo(r)}<span class="size-stamp">${r.size} cm</span></a><div class="card-copy">${badge(r)}<h3><a href="#/frog/${r.id}">${escape(r.name)}</a></h3><i>${escape(r.scientific)}</i>${r.location?`<p class="card-location"><span class="sr-only">Location: </span>${escape(r.location)}</p>`:''}<div class="card-bottom"><span>${escape(r.temperament)}</span><a href="#/frog/${r.id}" aria-label="Meet ${escape(r.name)}">↗</a></div></div></article>`).join(''):empty('Try a different name or habitat.');clearFilters(catalog);}
function detail(r){if(!r)return notFound();main.innerHTML=`<a class="back" href="#/">← Back to field guide</a><section class="detail">${photo(r,'',true)}<div class="detail-copy">${badge(r)}<h1>${escape(r.name)}</h1><i class="species">${escape(r.scientific)}</i><p class="description">${escape(r.description)}</p><dl class="attributes">${[['Size',r.size+' cm'],['Personality',r.temperament],['Habitat',r.habitat],['Location',r.location || 'Not recorded'],['Rarity',r.rarity],['Favorite food',r.diet],['Call',r.call]].map(([k,v])=>`<div><dt>${k}</dt><dd>${escape(v)}</dd></div>`).join('')}</dl><p class="fine-print">An imaginary species with an AI-generated portrait.</p><a class="text-link" href="#/admin/edit/${r.id}">Edit this frog ↗</a></div></section>`;document.title=`${r.name} · FrogDB`;}
function dashboard(){main.innerHTML=`${banner()}<section class="admin-heading"><div><h1>A well-tended pond.</h1><p>Give every frog its place in the field guide.</p></div><a class="button" href="#/admin/new">+ Add a frog</a></section><p class="demo-note"><strong>Your browser, your collection.</strong> This demo saves edits on this device. It has no login or shared database.</p><div class="admin-summary"><span><strong>${records.length}</strong> total frogs</span><span><strong>${records.filter(r=>r.status==='published').length}</strong> published</span><span><strong>${records.filter(r=>r.status==='draft').length}</strong> drafts</span></div><section class="admin-records"><div class="filters"><label class="search"><span class="sr-only">Search managed frogs</span><input id="search" type="search" placeholder="Search frogs or locations…" value="${escape(query)}"></label><label><span class="sr-only">Habitat</span><select id="habitat">${options(['All habitats',...habitats],habitat)}</select></label><label><span class="sr-only">Publication status</span><select id="status"><option value="all">All statuses</option><option value="published" ${status==='published'?'selected':''}>Published</option><option value="draft" ${status==='draft'?'selected':''}>Draft</option></select></label></div><div id="rows"></div></section><section class="data-tools"><div><h2>Keep a copy of your pond.</h2><p>Export a backup, or import a collection from another browser. Import replaces the current collection.</p></div><div class="actions"><button class="button secondary" id="export">Export JSON</button><label class="button secondary file-button">Import JSON<input type="file" id="import" accept="application/json,.json"></label></div></section><p id="import-error" role="alert"></p>`;wireFilters(true);document.querySelector('#status').addEventListener('change',e=>{status=e.target.value;drawRows();});drawRows();document.querySelector('#export').onclick=()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(records,null,2)],{type:'application/json'}));link.download='frogdb-collection.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);toast('Collection exported.');};document.querySelector('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2_000_000)throw new Error('Choose a JSON file smaller than 2 MB.');const next=validateRecords(JSON.parse(await file.text()));confirmAction('Replace your collection?',`This replaces all ${records.length} current frogs with ${next.length} imported frogs. Export a backup first if needed.`,'Replace collection',()=>{if(persist(next)){dashboard();toast('Collection imported.');}},'Keep collection');}catch(err){document.querySelector('#import-error').textContent=`Import failed. ${err.message}`;}e.target.value='';};}
function drawRows(){const list=filtered(true);document.querySelector('#rows').innerHTML=list.length?`<div class="table-wrap"><table><caption class="sr-only">Frog management, ${list.length} records</caption><thead><tr><th>Frog</th><th>Habitat</th><th>Size</th><th>Status</th><th><span class="sr-only">Actions</span></th></tr></thead><tbody>${list.map(r=>`<tr><td><a class="table-frog" href="#/admin/edit/${r.id}">${photo(r)}<span><strong>${escape(r.name)}</strong><i>${escape(r.scientific)}</i></span></a></td><td>${badge(r)}</td><td>${r.size} cm</td><td><span class="status ${r.status}">${r.status==='published'?'Published':'Draft'}</span></td><td class="row-actions"><a href="#/admin/edit/${r.id}" aria-label="Edit ${escape(r.name)}">Edit</a><button class="delete-link" data-delete="${r.id}" aria-label="Delete ${escape(r.name)}">Delete</button></td></tr>`).join('')}</tbody></table></div>`:empty('Change the filters, or add your first frog.');clearFilters(dashboard);document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const r=records.find(r=>r.id===b.dataset.delete);confirmAction(`Delete ${r.name}?`,'This removes the frog from this browser and its public field guide. This cannot be undone.','Delete frog',()=>{if(persist(records.filter(v=>v.id!==r.id))){dashboard();toast('Frog deleted.');}});});}
function confirmAction(title,copy,label,action,cancel='Keep frog'){const dialog=document.querySelector('#confirm-dialog');document.querySelector('#confirm-title').textContent=title;document.querySelector('#confirm-copy').textContent=copy;document.querySelector('#confirm-delete').textContent=label;document.querySelector('#confirm-cancel').textContent=cancel;document.querySelector('#confirm-cancel').onclick=()=>dialog.close();document.querySelector('#confirm-delete').onclick=()=>{dialog.close();action();};dialog.showModal();document.querySelector('#confirm-cancel').focus();}
function editor(existing){const isNew=location.hash==='#/admin/new';if(!isNew&&!existing)return notFound();const r=existing||{name:'',scientific:'',location:'',habitat:habitats[0],size:4,temperament:'',call:'',diet:'',rarity:'Common',portrait:0,status:'draft',description:''};const field=(label,key,placeholder='')=>`<label>${label}<input name="${key}" value="${escape(r[key])}" maxlength="100" placeholder="${placeholder}" required></label>`;
main.innerHTML=`<a class="back" href="#/admin">← Back to frog management</a><div class="editor-heading"><h1>${isNew?'A new face in the pond.':'A little fine-tuning.'}</h1><p>${isNew?'Start with a name. The personality will follow.':'Update this frog’s profile and publication status.'}</p></div><form id="frog-form" class="editor"><div class="form-body"><section><h2>The essentials</h2><div class="form-grid">${field('Common name','name','e.g. Moss-whiskered tree frog')}${field('Scientific name','scientific','e.g. Hyla muscosa')}<label>Location (optional)<input name="location" value="${escape(r.location)}" maxlength="100" placeholder="e.g. Velora Mist Highlands"></label><label>Habitat<select name="habitat">${options(habitats,r.habitat)}</select></label><label>Size in cm<input name="size" type="number" min="0.1" max="40" step="0.1" value="${r.size}" required></label></div></section><section><h2>A bit of character</h2><div class="form-grid">${field('Personality','temperament','e.g. Enthusiastic observer')}${field('Favorite food','diet','e.g. Small crickets')}${field('Call','call','e.g. A gentle evening trill')}<label>Rarity<select name="rarity">${options(['Common','Uncommon','Rare'],r.rarity)}</select></label></div><label class="wide-label">Field notes<textarea name="description" rows="5" maxlength="1200" required placeholder="What makes this frog a little extraordinary?">${escape(r.description)}</textarea><span class="field-help">Fictional details welcome. Up to 1,200 characters.</span></label></section></div><aside class="editor-side"><h2>Put a face to the name.</h2><fieldset><legend>Choose a portrait</legend><div class="portrait-picker">${portraits.map((name,i)=>`<label><input type="radio" name="portrait" value="${i}" ${r.portrait===i?'checked':''}><span class="portrait p${i}" style="background-position:${(i % 7) * 100 / 6}% ${Math.floor(i / 7) * 25}%" role="img" aria-label="${name}"></span><span>${name}</span></label>`).join('')}</div></fieldset><label class="publication-label">Publication status<select name="status">${options(['draft','published'],r.status)}</select></label><p class="field-help">Only published frogs appear in the public field guide. Changes are saved in this browser.</p><p id="form-error" role="alert"></p><button class="button save-button" type="submit">${isNew?'Save frog':'Save changes'}</button><a class="cancel-edit" href="#/admin">Cancel</a></aside></form>`;
const form=document.querySelector('#frog-form');form.addEventListener('input',()=>{dirty=true;});form.onsubmit=e=>{e.preventDefault();const value=Object.fromEntries(new FormData(form));value.id=existing?.id||crypto.randomUUID();try{const valid=validateRecords([value])[0];const next=existing?records.map(v=>v.id===existing.id?valid:v):[...records,valid];if(persist(next)){dirty=false;query='';habitat='All habitats';status='all';location.hash='/admin';toast(isNew?'New frog saved. Welcome to the pond.':'Frog updated.');}}catch(error){document.querySelector('#form-error').textContent=error.message;}};
}
function notFound(){main.innerHTML='<section class="not-found"><h1>This frog hopped away.</h1><p>The page may be missing, or the frog is still a draft.</p><a class="button" href="#/">Back to field guide</a></section>';}
document.addEventListener('click',e=>{const a=e.target.closest('a');const href=a?.getAttribute('href');if(dirty&&href?.startsWith('#/')&&href!==location.hash){if(!window.confirm('Leave without saving your frog?'))e.preventDefault();else dirty=false;}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('hashchange',e=>{if(dirty&&location.hash!=='#main'&&location.hash!=='#collection'&&!window.confirm('Leave without saving your frog?')){history.replaceState(null,'',e.oldURL);return;}if(location.hash==='#main'){main.focus();return;}if(location.hash==='#collection'){document.querySelector('#collection')?.scrollIntoView({behavior:'smooth'});return;}route();main.focus({preventScroll:true});});
window.addEventListener('storage',e=>{if(e.key==='frogdb.records.v1'&&!dirty){try{records=loadRecords(localStorage);route();toast('Collection updated from another tab.');}catch{toast('Could not read changes from the other tab.');}}});
route();


