export const habitats = ['Cloud forest', 'Riverbank', 'Wetland', 'Woodland'];
export const portraits = ['Fernbrow', 'Apricot frill', 'Blue-speckled', 'Lemon marsh','Copper reed','Plum throat','Mint glass','Rust moss','Pearl belly','Gold eye','Rose petal','Emerald toe','Silver eye','Chartreuse stripe','Cinnamon freckle','Lavender horn','Turquoise web','Honey dusk','Scarlet cream','Olive ridge','Frost blue','Burgundy spot','Jade velvet','Pumpkin pond','Smoky stone','Cream clover','Lime leaper','Indigo star','Coral creek','Chocolate ring','Pistachio puff','Violet hush','Brass bell','Seafoam glass','Inkdrop'];
export const seedFrogs = [
  {id:'fern-brow',name:'Fernbrow tree frog',scientific:'Hyla frondosa',habitat:'Cloud forest',size:4.8,temperament:'Quietly curious',call:'A soft, two-note whistle',diet:'Moths & tiny beetles',rarity:'Uncommon',portrait:0,status:'published',description:'A patient little canopy dweller with fern-like ridges above its eyes. It sits perfectly still through a rainstorm, then shakes every drop off at once. Field observers suspect it enjoys the drama.'},
  {id:'apricot-frill',name:'Apricot frill frog',scientific:'Litoria aurantina',habitat:'Riverbank',size:3.2,temperament:'Social butterfly',call:'Three bright little chirps',diet:'Fruit flies & midges',rarity:'Rare',portrait:1,status:'published',description:'Its translucent cheek frills flutter in even the smallest breeze. Usually found on warm river stones in groups of three, each apparently waiting for the others to say something.'},
  {id:'blue-speckled',name:'Blue-speckled rain frog',scientific:'Breviceps caeruleus',habitat:'Woodland',size:5.6,temperament:'Politely grumpy',call:'A surprisingly deep creak',diet:'Ants & leaf-litter insects',rarity:'Uncommon',portrait:2,status:'published',description:'A midnight-blue forest resident whose turquoise spots brighten after rain. It looks permanently unimpressed, but will happily spend an afternoon following a particularly interesting beetle.'},
  {id:'lemon-marsh',name:'Lemon marsh frog',scientific:'Rana citrinella',habitat:'Wetland',size:6.1,temperament:'Unhurried optimist',call:'One round, resonant plop',diet:'Mosquitoes & small crickets',rarity:'Common',portrait:3,status:'published',description:'Almost spherical when resting, this golden marsh frog prefers the shallow end of everything. Its tiny feet are surprisingly effective, though it generally considers hopping a last resort.'}
];
const extra = [
 ['Copper reed frog','Hyperolius cuprinus','Wetland',2.9,'Restless explorer','A reed-thin buzz','Gnats & water flies','Uncommon','Balances on reeds using its broad amber toes. Every sunset it moves to a new perch, even if the old one was perfectly good.'],
 ['Plum-throated dusk frog','Litoria prunica','Cloud forest',4.2,'Evening philosopher','A mellow descending hum','Moths & lacewings','Rare','A violet throat pouch gives this twilight singer its name. It pauses between calls as though reconsidering the entire conversation.'],
 ['Mint glass frog','Hyalinobatrachium mentha','Riverbank',2.1,'Delicate daydreamer','A faint glassy ping','Tiny flies','Rare','Its sea-green skin is almost translucent at the toes. It sleeps under broad leaves, with one eye open for passing raindrops.'],
 ['Rust-backed moss frog','Theloderma ferruga','Woodland',3.7,'Expert hide-and-seeker','A scratchy little click','Springtails & mites','Common','Warm rust-colored flecks blend into fallen leaves. The quickest way to find one is to wait for the leaf pile to blink.'],
 ['Pearl-bellied stream frog','Rana margarita','Riverbank',5.2,'Gentle drifter','A bubbling chime','Mayflies & midges','Uncommon','An ivory belly flashes when it hops across shallow streams. It prefers stones with a good view of absolutely nothing happening.'],
 ['Gold-eyed night frog','Nyctibatrachus aureoculus','Woodland',4.1,'After-hours enthusiast','Two low knocks','Beetles & small moths','Rare','Golden eyes catch the faintest woodland light. It spends the day wedged into bark and the night inspecting the same three puddles.'],
 ['Rose-petal puddle frog','Microhyla rosella','Wetland',2.4,'Shy optimist','A tiny rising squeak','Mosquito larvae','Uncommon','Dusty pink skin fades toward a pale cream belly. It takes shelter in flower litter, which is both practical and a little theatrical.'],
 ['Emerald broad-toed frog','Rhacophorus smaragdinus','Cloud forest',6.3,'Confident climber','A sharp wooden clack','Crickets & leaf insects','Common','Enormous toe pads let it cling to wet leaves. It has never encountered a branch it did not believe it could reach.'],
 ['Silver-eyed slate frog','Rana argyrops','Riverbank',4.9,'Careful observer','A soft gravelly croak','River flies','Uncommon','Its smooth grey back resembles a freshly washed stone. Silver eyes betray its camouflage whenever curiosity wins over caution.'],
 ['Chartreuse ribbon frog','Hyperolius taeniatus','Wetland',3.1,'Energetic neighbor','A rapid ticking chorus','Gnats & tiny moths','Common','Fine dark stripes run along its bright green sides. It calls in quick bursts, then waits impatiently for everyone else to catch up.'],
 ['Cinnamon freckle frog','Pristimantis cinnamomeus','Woodland',3.4,'Patient forager','A dry leaf-like rustle','Ants & termites','Common','Tiny cinnamon freckles break up its warm brown skin. It tests each fallen leaf with one toe before committing to a landing.'],
 ['Lavender horn frog','Ceratophrys lavandula','Woodland',7.8,'Dignified loaf','A low rounded honk','Large crickets','Rare','Two modest brow ridges give this lavender frog an air of authority. Its main administrative duty is remaining exactly where it is.'],
 ['Turquoise webfoot','Rhacophorus cyanodactylus','Cloud forest',5.8,'Fearless glider','A bright clipped trill','Moths & tree crickets','Uncommon','Vivid blue webbing fans out between long toes. Short glides end with a careful landing and what looks suspiciously like satisfaction.'],
 ['Honey dusk frog','Litoria mellita','Riverbank',4.6,'Warm-hearted wanderer','A gentle three-beat chirrup','Midges & beetles','Common','Amber skin glows under late afternoon light. It patrols the bank slowly, stopping often to study ripples made by other frogs.'],
 ['Scarlet cream-belly','Dyscophus rubrilacteus','Wetland',6.9,'Bold but bashful','A muffled trumpet','Crickets & small beetles','Rare','A scarlet back contrasts with a soft cream underside. Despite its conspicuous coloring, it behaves as if nobody can possibly see it.'],
 ['Olive ridgeback','Rana olivacrista','Woodland',5.5,'Steady companion','A rhythmic hollow knock','Woodlice & beetles','Common','Three ridges along its back channel rain toward its toes. It chooses the same resting log each night with admirable consistency.'],
 ['Frost-blue brook frog','Amolops glacialis','Riverbank',3.8,'Cool-headed thinker','A high, airy note','Stoneflies & midges','Rare','Pale blue skin and silvery joints make it look dusted with frost. It favors cool splash pools and avoids dramatic entrances.'],
 ['Burgundy spotted frog','Rana vinosa','Wetland',5.1,'Reserved storyteller','A slow, uneven croak','Water beetles','Uncommon','Wine-colored spots deepen around the shoulders. It starts calling only after every louder frog in the marsh has finished.'],
 ['Jade velvet frog','Litoria velutina','Cloud forest',4.4,'Soft-spoken climber','A breathy double chirp','Moths & katydids','Uncommon','A matte jade back catches light like velvet. It settles into curled leaves, leaving only its rounded nose visible from below.'],
 ['Pumpkin pond frog','Rana cucurbita','Wetland',6.6,'Cheerful homebody','A buoyant little gulp','Mosquitoes & crickets','Common','Its bright orange body makes it easy to spot among pond weeds. It maintains a favorite patch of mud with serious dedication.'],
 ['Smoky stone frog','Leptobrachium fumosum','Riverbank',7.2,'Unflappable sentinel','A deep sandy rumble','Beetles & worms','Uncommon','A broad, flat head and smoky skin resemble river cobbles. Water may rush around it for hours before it decides to shift one foot.'],
 ['Clover-spotted cream frog','Microhyla trifolia','Woodland',2.7,'Tiny perfectionist','Four delicate ticks','Springtails','Rare','Little green spots cluster across its pale back. It carefully wipes its face after meals, even when nobody else is watching.'],
 ['Lime longleg','Rhacophorus limonipes','Cloud forest',5.9,'Impatient acrobat','A sharp upward whistle','Flying ants & moths','Common','Long hind legs fold almost invisibly beneath its lime-green body. It measures distances with a stare and occasionally an optimistic second stare.'],
 ['Indigo star frog','Nyctibatrachus stellatus','Woodland',4.3,'Moonlight collector','A low bell-like pulse','Night moths','Rare','Small gold flecks scatter across an indigo back. In dim light it resembles a piece of night sky that has developed opinions about beetles.'],
 ['Coral creek frog','Litoria corallina','Riverbank',3.6,'Friendly interrupter','A quick bubbling trill','Creek flies','Uncommon','Salmon-colored cheeks brighten near running water. It joins neighboring calls half a beat early and seems delighted with the result.'],
 ['Chocolate ringeye','Rana annuloocula','Woodland',5.7,'Thoughtful ambler','A soft rolling croak','Woodlice & worms','Common','Pale rings around its eyes contrast with dark cocoa skin. It has the look of a frog that remembers where it left every useful leaf.'],
 ['Pistachio puff frog','Breviceps pistacinus','Wetland',4.7,'Contented little lump','A squeaky exhale','Ants & termites','Uncommon','A squat pistachio body rests on surprisingly small feet. When startled it inflates slightly, then appears embarrassed by the attention.'],
 ['Violet hush frog','Pristimantis violaceus','Cloud forest',2.8,'Quiet adventurer','An almost inaudible peep','Tiny moths','Rare','Dusky violet skin disappears into the shaded canopy. Its quiet call is usually mistaken for a leaf brushing another leaf.'],
 ['Brass bell frog','Rana campanula','Wetland',6.4,'Enthusiastic vocalist','A resonant metallic bong','Dragonfly nymphs','Uncommon','A brass-gold sheen covers its broad back. It practices its call from the edge of a hollow stump, evidently appreciating the acoustics.'],
 ['Seafoam glassleaf','Hyalinobatrachium spumans','Cloud forest',2.3,'Rain-loving recluse','A clear single ping','Fruit flies','Rare','Seafoam-green limbs become translucent near the edges. It shelters on leaf undersides and emerges only for rain worth getting wet in.'],
 ['Inkdrop snow frog','Rana atronivea','Riverbank',4.5,'Curious eccentric','A short paper-like rasp','Midges & small beetles','Rare','Black freckles dot a creamy white back like spilled ink. Every frog has a different pattern, and none seems willing to explain it.']
];
extra.forEach(([name,scientific,habitat,size,temperament,call,diet,rarity,description],i)=>seedFrogs.push({id:name.toLowerCase().replaceAll(' ','-'),name,scientific,habitat,size,temperament,call,diet,rarity,description,portrait:i+4,status:'published'}));
